version: '3'
services:
  python:
    build:
      context: .
    
    depends_on:
      - postgres
    
    user: vscode
    container_name: python-vscode
    volumes:
      - ~/workspace:/workspace
      - ~/.ssh:/root/.ssh-localhost:ro
    environment:
      - DB_HOST=postgres
      - DB_NAME=app
      - DB_USER=app

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - 8000:8000

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_HOST_AUTH_METHOD=trust
