version: '3'
services:
  python:
    build:
      context: .
    
    depends_on:
      - postgres
    
    user: vscode
    container_name: python-vscode
    volumes:
      - ~/workspace:/workspace
      - ~/.ssh:/root/.ssh-localhost:ro

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - 8000:8000


  postgres:
    image: postgres:12-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
