FROM rust:1.63.0

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Configure apt and install packages
RUN apt-get update \
    && apt-get -y install --no-install-recommends build-essential curl apt-utils dialog 2>&1 \
    # Verify git, process tools, lsb-release (common in install instructions for CLIs) installed
    && apt-get -y install git iproute2 procps lsb-release \
    # Create a non-root user to use if preferred - see https://aka.ms/vscode-remote/containers/non-root-user.
    && groupadd --gid $USER_GID $USERNAME \
    && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Tweak bashrc
USER $USERNAME 
RUN rustup component add rustfmt clippy
RUN echo "alias ls='ls --color=auto'" >> ~/.bash_aliases \
    && echo "alias ll='ls -la'" >> ~/.bash_aliases \
    && echo "alias l='ls -d .* --color=auto'" >> ~/.bash_aliases    

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=
